### PR TITLE
Add org.doctales.terminology

### PR DESCRIPTION
**Pull request by xephon2**
Add `org.doctales.terminology`, a DITA-OT plugin and authoring framework for terminology management, that generates Schematron termchecker rule sets from DITA `<termentry>` topics.

### CODE REVIEW

**Comment by xephon2** [comment]
@tkg 🎶

**Comment by tgraham-antenna** [comment]
Does anyone else use it who could vouch for it being 'awesome'?

(The problem with saying that this repository is a 'curated list' is that it shouldn't just list every known Schematron application, but I'm still working out what it means to curate the list.)

**Comment by xephon2** [comment]
I don't know, it only has 5 stars on Github. Just thought, you may have overlooked the PR. If you don't think it fits, just close the PR.

**Comment by tgraham-antenna** [comment]
No, it wasn't overlooked, and, yes, it does fit.  Your several watchers from outside the &lt;DOCTALES> project were good enough proof at this point, so I've merged the PR, thank you.

**Pull request merged**
